# 1. Conexión a la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lavadero_db
spring.datasource.username=postgres
spring.datasource.password=jose1803chinchilla
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate / JPA (El puente entre Java y SQL)
# Usamos "none" para que Java NO intente borrar ni modificar nuestras tablas con el escudo anti-superposición
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Para ver en la terminal las consultas SQL que hace Java en tiempo real (Excelente para aprender y probar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Puerto donde correrá nuestro servidor web (por defecto es el 8080)
server.port=8080